"""Build an offline SQLite Pokedex database from PokeAPI.

Default output:
    app/data/pokedex.sqlite

Example:
    python tools/build_pokedex_db.py

This script fetches Pokemon, species, evolution, version, and version-group
resources from https://pokeapi.co. Responses are cached locally so interrupted
builds can be resumed without refetching everything.

Generated by GPT 5.5 using Codex
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sqlite3
import time
from pathlib import Path
from typing import Any

import requests


API_BASE = "https://pokeapi.co/api/v2/"
DEFAULT_LIMIT = 1025
REGIONAL_FORM_MARKERS = ("-alola", "-galar", "-hisui", "-paldea")


class PokeApiClient:
    def __init__(self, cache_dir: Path, sleep_seconds: float = 0.05) -> None:
        self.cache_dir = cache_dir
        self.sleep_seconds = sleep_seconds
        self.session = requests.Session()
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def get(self, path: str) -> dict[str, Any]:
        return self.get_url(API_BASE + path.lstrip("/"))

    def get_url(self, url: str) -> dict[str, Any]:
        cache_path = self._cache_path(url)
        if cache_path.exists():
            return json.loads(cache_path.read_text(encoding="utf-8"))

        for attempt in range(1, 4):
            try:
                response = self.session.get(url, timeout=30)
                response.raise_for_status()
                data = response.json()
                cache_path.write_text(
                    json.dumps(data, ensure_ascii=False, indent=2),
                    encoding="utf-8",
                )
                if self.sleep_seconds:
                    time.sleep(self.sleep_seconds)
                return data
            except requests.RequestException:
                if attempt == 3:
                    raise
                time.sleep(attempt * 2)

        raise RuntimeError(f"Unable to fetch {url}")

    def _cache_path(self, url: str) -> Path:
        digest = hashlib.sha256(url.encode("utf-8")).hexdigest()
        name = re.sub(r"[^a-zA-Z0-9_-]+", "_", url.replace(API_BASE, ""))
        return self.cache_dir / f"{name[:80]}_{digest[:12]}.json"


def resource_id(resource: dict[str, Any] | None) -> int | None:
    if not resource:
        return None
    url = resource.get("url", "")
    parts = [part for part in url.rstrip("/").split("/") if part]
    if not parts:
        return None
    try:
        return int(parts[-1])
    except ValueError:
        return None


def clean_text(text: str) -> str:
    return " ".join(text.replace("\f", " ").replace("\n", " ").split())


def json_dump(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def create_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(
        """
        PRAGMA foreign_keys = ON;

        CREATE TABLE metadata (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        );

        CREATE TABLE generations (
            name TEXT PRIMARY KEY,
            api_id INTEGER NOT NULL
        );

        CREATE TABLE version_groups (
            name TEXT PRIMARY KEY,
            api_id INTEGER NOT NULL,
            generation_name TEXT NOT NULL REFERENCES generations(name)
        );

        CREATE TABLE versions (
            name TEXT PRIMARY KEY,
            api_id INTEGER NOT NULL,
            version_group_name TEXT NOT NULL REFERENCES version_groups(name),
            generation_name TEXT NOT NULL REFERENCES generations(name)
        );

        CREATE TABLE pokemon (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            national_dex_id INTEGER NOT NULL,
            species_id INTEGER NOT NULL,
            species_name TEXT NOT NULL,
            form_name TEXT,
            is_default INTEGER NOT NULL,
            height_dm INTEGER,
            weight_hg INTEGER,
            base_experience INTEGER,
            growth_rate TEXT,
            base_friendship INTEGER,
            hatch_counter INTEGER,
            capture_rate INTEGER,
            is_baby INTEGER NOT NULL,
            is_legendary INTEGER NOT NULL,
            is_mythical INTEGER NOT NULL
        );

        CREATE TABLE pokemon_types (
            pokemon_id INTEGER NOT NULL REFERENCES pokemon(id),
            slot INTEGER NOT NULL,
            type_name TEXT NOT NULL,
            PRIMARY KEY (pokemon_id, slot)
        );

        CREATE TABLE pokemon_abilities (
            pokemon_id INTEGER NOT NULL REFERENCES pokemon(id),
            slot INTEGER NOT NULL,
            ability_name TEXT NOT NULL,
            is_hidden INTEGER NOT NULL,
            PRIMARY KEY (pokemon_id, slot)
        );

        CREATE TABLE pokemon_stats (
            pokemon_id INTEGER NOT NULL REFERENCES pokemon(id),
            stat_name TEXT NOT NULL,
            base_stat INTEGER NOT NULL,
            ev_yield INTEGER NOT NULL,
            PRIMARY KEY (pokemon_id, stat_name)
        );

        CREATE TABLE egg_groups (
            pokemon_id INTEGER NOT NULL REFERENCES pokemon(id),
            egg_group_name TEXT NOT NULL,
            PRIMARY KEY (pokemon_id, egg_group_name)
        );

        CREATE TABLE pokemon_moves (
            pokemon_id INTEGER NOT NULL REFERENCES pokemon(id),
            move_name TEXT NOT NULL,
            generation_name TEXT NOT NULL REFERENCES generations(name),
            version_group_name TEXT NOT NULL REFERENCES version_groups(name),
            learn_method TEXT NOT NULL,
            level_learned_at INTEGER NOT NULL,
            details_json TEXT NOT NULL,
            PRIMARY KEY (
                pokemon_id,
                move_name,
                version_group_name,
                learn_method,
                level_learned_at
            )
        );

        CREATE TABLE pokedex_entries (
            species_id INTEGER NOT NULL,
            species_name TEXT NOT NULL,
            generation_name TEXT NOT NULL REFERENCES generations(name),
            version_name TEXT NOT NULL REFERENCES versions(name),
            language TEXT NOT NULL,
            flavor_text TEXT NOT NULL,
            PRIMARY KEY (species_id, version_name, language, flavor_text)
        );

        CREATE TABLE evolution_chains (
            chain_id INTEGER PRIMARY KEY
        );

        CREATE TABLE evolution_edges (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            chain_id INTEGER NOT NULL REFERENCES evolution_chains(chain_id),
            from_species_id INTEGER NOT NULL,
            from_species_name TEXT NOT NULL,
            to_species_id INTEGER NOT NULL,
            to_species_name TEXT NOT NULL,
            trigger_name TEXT,
            min_level INTEGER,
            item_name TEXT,
            held_item_name TEXT,
            known_move_name TEXT,
            known_move_type_name TEXT,
            location_name TEXT,
            min_happiness INTEGER,
            min_beauty INTEGER,
            min_affection INTEGER,
            time_of_day TEXT,
            gender INTEGER,
            needs_overworld_rain INTEGER,
            turn_upside_down INTEGER,
            party_species_name TEXT,
            party_type_name TEXT,
            relative_physical_stats INTEGER,
            trade_species_name TEXT,
            raw_details_json TEXT NOT NULL
        );

        CREATE INDEX idx_pokemon_name ON pokemon(name);
        CREATE INDEX idx_pokemon_national_dex ON pokemon(national_dex_id);
        CREATE INDEX idx_moves_pokemon_generation ON pokemon_moves(pokemon_id, generation_name);
        CREATE INDEX idx_moves_method ON pokemon_moves(learn_method);
        CREATE INDEX idx_entries_species_generation ON pokedex_entries(species_id, generation_name);
        CREATE INDEX idx_evolution_from ON evolution_edges(from_species_id);
        CREATE INDEX idx_evolution_to ON evolution_edges(to_species_id);
        """
    )


def insert_metadata(conn: sqlite3.Connection, key: str, value: Any) -> None:
    conn.execute(
        "INSERT OR REPLACE INTO metadata (key, value) VALUES (?, ?)",
        (key, str(value)),
    )


def build_version_maps(
    conn: sqlite3.Connection,
    api: PokeApiClient,
) -> tuple[dict[str, str], dict[str, str]]:
    generation_by_version_group: dict[str, str] = {}
    generation_by_version: dict[str, str] = {}

    generations = api.get("generation?limit=100")
    for item in generations["results"]:
        generation = api.get_url(item["url"])
        generation_name = generation["name"]
        conn.execute(
            "INSERT OR IGNORE INTO generations (name, api_id) VALUES (?, ?)",
            (generation_name, generation["id"]),
        )

    version_groups = api.get("version-group?limit=200")
    for item in version_groups["results"]:
        version_group = api.get_url(item["url"])
        group_name = version_group["name"]
        generation_name = version_group["generation"]["name"]
        generation_by_version_group[group_name] = generation_name
        conn.execute(
            """
            INSERT OR IGNORE INTO version_groups (name, api_id, generation_name)
            VALUES (?, ?, ?)
            """,
            (group_name, version_group["id"], generation_name),
        )

        for version in version_group["versions"]:
            version_name = version["name"]
            generation_by_version[version_name] = generation_name
            conn.execute(
                """
                INSERT OR IGNORE INTO versions (
                    name,
                    api_id,
                    version_group_name,
                    generation_name
                )
                VALUES (?, ?, ?, ?)
                """,
                (
                    version_name,
                    resource_id(version),
                    group_name,
                    generation_name,
                ),
            )

    return generation_by_version_group, generation_by_version


def insert_pokemon_core(
    conn: sqlite3.Connection,
    pokemon: dict[str, Any],
    species: dict[str, Any],
    is_default: bool,
) -> None:
    conn.execute(
        """
        INSERT OR REPLACE INTO pokemon (
            id,
            name,
            national_dex_id,
            species_id,
            species_name,
            form_name,
            is_default,
            height_dm,
            weight_hg,
            base_experience,
            growth_rate,
            base_friendship,
            hatch_counter,
            capture_rate,
            is_baby,
            is_legendary,
            is_mythical
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            pokemon["id"],
            pokemon["name"],
            species["id"],
            species["id"],
            species["name"],
            None if is_default else pokemon["name"],
            int(is_default),
            pokemon.get("height"),
            pokemon.get("weight"),
            pokemon.get("base_experience"),
            species.get("growth_rate", {}).get("name"),
            species.get("base_happiness"),
            species.get("hatch_counter"),
            species.get("capture_rate"),
            int(bool(species.get("is_baby"))),
            int(bool(species.get("is_legendary"))),
            int(bool(species.get("is_mythical"))),
        ),
    )

    for item in pokemon["types"]:
        conn.execute(
            """
            INSERT OR REPLACE INTO pokemon_types (pokemon_id, slot, type_name)
            VALUES (?, ?, ?)
            """,
            (pokemon["id"], item["slot"], item["type"]["name"]),
        )

    for item in pokemon["abilities"]:
        conn.execute(
            """
            INSERT OR REPLACE INTO pokemon_abilities (
                pokemon_id,
                slot,
                ability_name,
                is_hidden
            )
            VALUES (?, ?, ?, ?)
            """,
            (
                pokemon["id"],
                item["slot"],
                item["ability"]["name"],
                int(bool(item["is_hidden"])),
            ),
        )

    for item in pokemon["stats"]:
        conn.execute(
            """
            INSERT OR REPLACE INTO pokemon_stats (
                pokemon_id,
                stat_name,
                base_stat,
                ev_yield
            )
            VALUES (?, ?, ?, ?)
            """,
            (
                pokemon["id"],
                item["stat"]["name"],
                item["base_stat"],
                item["effort"],
            ),
        )

    for egg_group in species["egg_groups"]:
        conn.execute(
            """
            INSERT OR IGNORE INTO egg_groups (pokemon_id, egg_group_name)
            VALUES (?, ?)
            """,
            (pokemon["id"], egg_group["name"]),
        )


def insert_moves(
    conn: sqlite3.Connection,
    pokemon: dict[str, Any],
    generation_by_version_group: dict[str, str],
) -> None:
    for move in pokemon["moves"]:
        move_name = move["move"]["name"]
        for detail in move["version_group_details"]:
            version_group_name = detail["version_group"]["name"]
            generation_name = generation_by_version_group.get(version_group_name)
            if generation_name is None:
                continue

            learn_method = detail["move_learn_method"]["name"]
            if learn_method not in {"level-up", "machine"}:
                continue

            conn.execute(
                """
                INSERT OR IGNORE INTO pokemon_moves (
                    pokemon_id,
                    move_name,
                    generation_name,
                    version_group_name,
                    learn_method,
                    level_learned_at,
                    details_json
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    pokemon["id"],
                    move_name,
                    generation_name,
                    version_group_name,
                    learn_method,
                    detail["level_learned_at"],
                    json_dump(detail),
                ),
            )


def insert_pokedex_entries(
    conn: sqlite3.Connection,
    species: dict[str, Any],
    generation_by_version: dict[str, str],
    language: str,
) -> None:
    for entry in species["flavor_text_entries"]:
        if entry["language"]["name"] != language:
            continue

        version_name = entry["version"]["name"]
        generation_name = generation_by_version.get(version_name)
        if generation_name is None:
            continue

        conn.execute(
            """
            INSERT OR IGNORE INTO pokedex_entries (
                species_id,
                species_name,
                generation_name,
                version_name,
                language,
                flavor_text
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                species["id"],
                species["name"],
                generation_name,
                version_name,
                language,
                clean_text(entry["flavor_text"]),
            ),
        )


def insert_evolution_chain(
    conn: sqlite3.Connection,
    chain: dict[str, Any],
) -> None:
    chain_id = chain["id"]
    conn.execute(
        "INSERT OR IGNORE INTO evolution_chains (chain_id) VALUES (?)",
        (chain_id,),
    )

    def walk(node: dict[str, Any]) -> None:
        from_species = node["species"]
        from_species_id = resource_id(from_species)

        for child in node["evolves_to"]:
            to_species = child["species"]
            to_species_id = resource_id(to_species)
            details = child.get("evolution_details") or [{}]

            for detail in details:
                conn.execute(
                    """
                    INSERT INTO evolution_edges (
                        chain_id,
                        from_species_id,
                        from_species_name,
                        to_species_id,
                        to_species_name,
                        trigger_name,
                        min_level,
                        item_name,
                        held_item_name,
                        known_move_name,
                        known_move_type_name,
                        location_name,
                        min_happiness,
                        min_beauty,
                        min_affection,
                        time_of_day,
                        gender,
                        needs_overworld_rain,
                        turn_upside_down,
                        party_species_name,
                        party_type_name,
                        relative_physical_stats,
                        trade_species_name,
                        raw_details_json
                    )
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        chain_id,
                        from_species_id,
                        from_species["name"],
                        to_species_id,
                        to_species["name"],
                        optional_name(detail.get("trigger")),
                        detail.get("min_level"),
                        optional_name(detail.get("item")),
                        optional_name(detail.get("held_item")),
                        optional_name(detail.get("known_move")),
                        optional_name(detail.get("known_move_type")),
                        optional_name(detail.get("location")),
                        detail.get("min_happiness"),
                        detail.get("min_beauty"),
                        detail.get("min_affection"),
                        detail.get("time_of_day"),
                        detail.get("gender"),
                        int(bool(detail.get("needs_overworld_rain"))),
                        int(bool(detail.get("turn_upside_down"))),
                        optional_name(detail.get("party_species")),
                        optional_name(detail.get("party_type")),
                        detail.get("relative_physical_stats"),
                        optional_name(detail.get("trade_species")),
                        json_dump(detail),
                    ),
                )

            walk(child)

    walk(chain["chain"])


def optional_name(resource: dict[str, Any] | None) -> str | None:
    if resource is None:
        return None
    return resource.get("name")


def ensure_form_columns(conn: sqlite3.Connection) -> None:
    columns = {
        row[1]
        for row in conn.execute("PRAGMA table_info(pokemon)").fetchall()
    }

    if "national_dex_id" not in columns:
        conn.execute("ALTER TABLE pokemon ADD COLUMN national_dex_id INTEGER")
        conn.execute("UPDATE pokemon SET national_dex_id = species_id")

    if "form_name" not in columns:
        conn.execute("ALTER TABLE pokemon ADD COLUMN form_name TEXT")

    if "is_default" not in columns:
        conn.execute(
            "ALTER TABLE pokemon ADD COLUMN is_default INTEGER NOT NULL DEFAULT 1"
        )

    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_pokemon_national_dex ON pokemon(national_dex_id)"
    )


def is_regional_form(pokemon_name: str) -> bool:
    return any(marker in pokemon_name for marker in REGIONAL_FORM_MARKERS)


def selected_varieties(
    species: dict[str, Any],
    form_scope: str,
) -> list[dict[str, Any]]:
    if form_scope == "none":
        return []

    varieties = []
    for variety in species["varieties"]:
        if variety["is_default"]:
            continue

        pokemon_name = variety["pokemon"]["name"]
        if form_scope == "regional" and not is_regional_form(pokemon_name):
            continue

        varieties.append(variety)

    return varieties


def insert_complete_pokemon(
    conn: sqlite3.Connection,
    pokemon: dict[str, Any],
    species: dict[str, Any],
    generation_by_version_group: dict[str, str],
    generation_by_version: dict[str, str],
    language: str,
    is_default: bool,
) -> None:
    insert_pokemon_core(conn, pokemon, species, is_default=is_default)
    insert_moves(conn, pokemon, generation_by_version_group)
    insert_pokedex_entries(conn, species, generation_by_version, language)


def build_database(args: argparse.Namespace) -> None:
    output_path = Path(args.output)
    cache_dir = Path(args.cache_dir)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists():
        output_path.unlink()

    api = PokeApiClient(cache_dir=cache_dir, sleep_seconds=args.sleep)
    conn = sqlite3.connect(output_path)

    try:
        create_schema(conn)
        insert_metadata(conn, "source", API_BASE)
        insert_metadata(conn, "pokemon_limit", args.limit)
        insert_metadata(conn, "language", args.language)
        insert_metadata(conn, "form_scope", args.form_scope)
        insert_metadata(conn, "built_at_unix", int(time.time()))

        generation_by_version_group, generation_by_version = build_version_maps(
            conn,
            api,
        )

        seen_evolution_chains: set[int] = set()

        for pokemon_id in range(1, args.limit + 1):
            print(f"Fetching Pokemon {pokemon_id}/{args.limit}")
            pokemon = api.get(f"pokemon/{pokemon_id}")
            species = api.get_url(pokemon["species"]["url"])

            insert_complete_pokemon(
                conn,
                pokemon,
                species,
                generation_by_version_group,
                generation_by_version,
                args.language,
                is_default=True,
            )

            for variety in selected_varieties(species, args.form_scope):
                form_pokemon = api.get_url(variety["pokemon"]["url"])
                print(f"Fetching form {form_pokemon['name']}")
                insert_complete_pokemon(
                    conn,
                    form_pokemon,
                    species,
                    generation_by_version_group,
                    generation_by_version,
                    args.language,
                    is_default=False,
                )

            evolution_chain_id = resource_id(species["evolution_chain"])
            if evolution_chain_id not in seen_evolution_chains:
                chain = api.get_url(species["evolution_chain"]["url"])
                insert_evolution_chain(conn, chain)
                seen_evolution_chains.add(evolution_chain_id)

            if pokemon_id % args.commit_every == 0:
                conn.commit()

        conn.commit()
        print(f"Done. Wrote {output_path}")
    finally:
        conn.close()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build an offline SQLite Pokedex database from PokeAPI.",
    )
    parser.add_argument(
        "--output",
        default="app/data/pokedex.sqlite",
        help="SQLite database path to create.",
    )
    parser.add_argument(
        "--cache-dir",
        default=".cache/pokeapi",
        help="Directory used to cache PokeAPI JSON responses.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=DEFAULT_LIMIT,
        help="Number of National Dex Pokemon to fetch.",
    )
    parser.add_argument(
        "--language",
        default="en",
        help="Flavor text language code.",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.05,
        help="Seconds to sleep after uncached API requests.",
    )
    parser.add_argument(
        "--commit-every",
        type=int,
        default=25,
        help="Commit progress after this many Pokemon.",
    )
    parser.add_argument(
        "--form-scope",
        choices=("none", "regional", "all"),
        default="none",
        help=(
            "Include no non-default forms, only regional forms, or all PokeAPI "
            "varieties in the database build."
        ),
    )
    return parser.parse_args()


if __name__ == "__main__":
    build_database(parse_args())
